### ISSUE TITLE
Optimize all images

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/kineticimaging#15]
Right now the homepage pic is 4mb and some of the headers on other pages are pretty hefty also 
We should probably save most of them to jpegs at 65% or so quality instead of the pngs

![ccrkick](https://cloud.githubusercontent.com/assets/6132788/8556339/78654940-24c4-11e5-8ee3-7751933befdf.gif)

**Comment by PeytonSorah** [comment]
foh sho, going through and doing this now
