### ISSUE TITLE
Faculty slider needs vimeo and soundcloud support 

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/kineticimaging#22]
![giphy](https://cloud.githubusercontent.com/assets/1740634/8606162/ea2e8750-2657-11e5-9e27-769b0a8bc278.gif)

**Comment by dstrogiy** [comment]
![business](https://cloud.githubusercontent.com/assets/6132788/8606187/150f5378-2658-11e5-95f9-66ecad21a66c.gif)

**Comment by streeetlamp** [comment]
its got em
