### ISSUE TITLE
search X

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/kineticimaging#26]

**Comment by streeetlamp** [comment]
whats this?

**Comment by dstrogiy** [comment]
![screen shot 2015-07-15 at 2 31 59 pm](https://cloud.githubusercontent.com/assets/6132788/8706533/436c6f26-2afe-11e5-8a36-b1e31e56e1b6.png)

**Comment by PeytonSorah** [comment]
oh lol, i didn't realize that i had forgotten to write a description. 

we just got too many damn x's up in here: 
<img width="167" alt="screen shot 2015-07-15 at 2 44 43 pm" src="https://cloud.githubusercontent.com/assets/7943826/8706864/1ab03f98-2b00-11e5-9064-8971e960ba73.png">
<img width="182" alt="screen shot 2015-07-15 at 2 44 50 pm" src="https://cloud.githubusercontent.com/assets/7943826/8706863/1aaf0eca-2b00-11e5-8fe3-15a938e7b413.png">
<img width="146" alt="screen shot 2015-07-15 at 2 44 58 pm" src="https://cloud.githubusercontent.com/assets/7943826/8706865/1ab28df2-2b00-11e5-8286-6877d8e70084.png">

**Comment by streeetlamp** [comment]
![bm3faf8](https://cloud.githubusercontent.com/assets/1740634/8753167/6dac9114-2c87-11e5-8863-cce3616e495b.gif)
