### ISSUE TITLE
height issue on gallery/visiting artist pages 

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/kineticimaging#3]
On first page load, content gets pushed into footer- after refresh it's fine.

**Comment by dstrogiy** [comment]
I think we can try to wrap the whole gallery in a div and add a min-height to it - that way the footer should stay down

**Comment by streeetlamp** [comment]
its probably because document.ready() doesn't wait for images, will fix

**Comment by streeetlamp** [comment]
should be fixed now

**Comment by dstrogiy** [comment]
![screen shot 2015-07-08 at 1 55 09 pm](https://cloud.githubusercontent.com/assets/6132788/8577785/057ed8aa-2579-11e5-89e3-8bfc85b062eb.png)
