### ISSUE TITLE
Display main nav on window-resize

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/kineticimaging#38]
If you resize screen to mobile, then open & close the nav, and resize screen back to desktop, the nav disappears.

Need to assign display-block on window-resize above 900px

**Comment by streeetlamp** [comment]
![vlvgvqp](https://cloud.githubusercontent.com/assets/1740634/8754112/2c028dec-2c8f-11e5-96cc-458d7f2cf9b0.gif)
