### ISSUE TITLE
Etc.

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/kineticimaging#4]
- [x] Social Links
- [x] Typography Consistency 
- [x] x on search should match x on hamburger nav
- [x] paragraph on front page should be pulled from ACF
- [x] visiting artists hover
- [x] placement of name/work on front page slider (should sit in corner 25px from side 25px from bottom of box) 
- [x] squiggle hover on main nav?? (wasn't sure about this because they nuked squiggle bg)

**Comment by dstrogiy** [comment]
- [ ] Active nav item should be different color or something
- [ ] transitions - we could do some subtle transitions on all the links, especially the latest news circles

**Comment by dstrogiy** [comment]
- [ ] raw page title finesse
![screen shot 2015-07-08 at 10 13 26 am](https://cloud.githubusercontent.com/assets/6132788/8572331/ff5586a0-2559-11e5-863c-bd74a8152c90.png)

**Comment by dstrogiy** [comment]
I think we should do the squiggle btw, either for hover or active nav

**Comment by streeetlamp** [comment]
i can draw the squiggle with my SVG library too 👀

**Comment by dstrogiy** [comment]
I propose to make the packery images that aren't loaded to be black instead of light gray

**Comment by streeetlamp** [comment]
they be black now, yuhh
