### ISSUE TITLE
Request/Edits from the KI crew

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/kineticimaging#41]
- [x] reduce the size of images on visiting artists and gallery (B & J)

- [x] reduce the white lines across the board/ specifically on contact us (J)

- [x] increase left and right padding on Identity box on home page (J)

- [x] line height/spacing should be a little bit tighter on the image captions (J)

- [x] The blocky-ness is a bit exhausting on News, it needs something that'll give the eyes a rest or some sort of playfulness that isn't hidden. I say this because the hover animations are pretty sweet, but you don't know about them unless you hover over something. Maybe it needs the blocks to vary in different sizes?  (J)

- [x] links that take you off the site open up to new tabs (J)

- [ ] reduce gifs or make less jarring (B)

- [x]  About: There's something perhaps a tad off in the column on the right ("Students"). Not quite sure what. Perhaps we can bold the first word of each point, emphasizing the active verb (ENGAGE/LEARN/EXPLORE, etc.). That might involve a slight rewrite, "Discover" instead of the 2nd "Learn" and so on.  (B)

- [x]  About: one typo. The phrase "engage in critical thinking IS an active..." should probably be "engage in critical thinking AS an active…" (B)

- [x]  two pages under "Program" — one for undergrad, one for grad. (B)

- [x]  Check out the first link in the undergraduate section ("View descriptions of courses offered in Kinetic Imaging). It doesn't seem right. (B)

- [x]  we're leaving behind the idea of a page for each grad student (complete with art statement, etc.). The only representation of our grad program is this collected (and kind of chaotic) gallery. Do we want that? (B)

- [x]  Faculty: Quite clean and clear. The big issue here is, again, the question of BIGNESS. I'm afraid for me, this is similar to the gallery. That is, why are these rectangles so BIG? Is the text for senior citizens? It just seems that a smaller size will look way more sleek and be easier to take in at a glance. Again, this is only my two cents, and I certainly respect that someone else may prefer this brash size.(B)

- [x]   I'm also not crazy about the white borders on the images. I think Jess might have mentioned this too. With the black background providing sharp contrast for and images, I don't see the need for them. (B)

- [x]  put the highest degree first  on faculty and others below (B) 

- [x] News: I wonder why the space and text is so big, and the image is so small. (B)

**Comment by streeetlamp** [comment]
thxxx
