### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/kineticimaging#52]
- [x] Make the logo a bit smaller

- [x] Titles that are two lines get too close to content, we need to switch them to relative positioning so that they are flexible

![img_4846](https://cloud.githubusercontent.com/assets/6132788/8755512/5695873a-2c99-11e5-9872-d0f78d08100b.PNG)

**Comment by dstrogiy** [comment]
All 3 are good, except now when you scroll the nav, the page behind it scrolls, but the nav stays in the same place lol

**Comment by streeetlamp** [comment]
![70p2nlj](https://cloud.githubusercontent.com/assets/1740634/8756095/92a84b28-2c9d-11e5-8029-ea93ad681707.gif)

**Comment by dstrogiy** [comment]
![bad-day](https://cloud.githubusercontent.com/assets/6132788/8756236/c45c060e-2c9e-11e5-8658-b9bffbd1023f.gif)
