### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/kineticimaging#56]
- [x] hero image height to 90vh
- [x] Identity title - rename to Mission Statement
- [x] Circles - individual pink outlines like in Cody's 1st comp, maybe remove the white border if we do that
- [x] Possibly no lines around KI identity text either
- [x] Swap news & identity places, so that the you can preview a bit of text right under hero without scrolling

**Comment by streeetlamp** [comment]
![giphy](https://cloud.githubusercontent.com/assets/1740634/8911534/0ac7e4a0-345b-11e5-9e6f-029f7b26a7e1.gif)
